change from id -gn to stat -c %G
Redo this commit because it broke OSX
For consistancy, use the user/group of the home directory instead of the
current process since it's more about the filesystem than anything else.

diff --git a/bin/vertica-setup b/bin/vertica-setup
--- a/bin/vertica-setup
+++ b/bin/vertica-setup
@@ -51,29 +51,35 @@ docker container rm $CONTAINER_NAME 2>/dev/null
 
 docker run --detach "${DOCKER_RUNARGS[@]}" "${VERTICA_ENV[@]}" "$DOCKER_IMAGE" || abort $? "Could not create docker"
 
-# create a local user with the same home directory
-: ${LOGNAME:=$(stat -c "%U" "$HOME")} # if LOGNAME is not set, use the owner of the home directory
-: ${USERID:=$(docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME stat -c "%u:%g" "$HOME")}
-HOME_GROUP=$(id -gn 2>/dev/null) # the group name
-: ${HOME_GROUP:=$(getent group $(id -g) | cut -d: -f1)} # just in case id -gn is not supported
+# user in container should match the home directory
+if [[ $OSTYPE == darwin* ]]; then # OSX uses different args for stat
+  : ${LOGNAME:=$(stat -f "%Su" "$HOME")} # if LOGNAME is not set, use the owner of the home directory
+  : ${LOGGROUP:=$(stat -f "%Sg" "$HOME")}
+else
+  : ${LOGNAME:=$(stat -c "%U" "$HOME")} # if LOGNAME is not set, use the owner of the home directory
+  : ${LOGGROUP:=$(stat -c "%G" "$HOME")}
+fi
 
-# add user to sudoers
-docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo bash -c "echo '$LOGNAME ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers" || abort $? "Could not give $LOGNAME sudo access"
+# determine uid/gid of mounted home directory (in case docker maps to a different id)
+: ${USERID:=$(docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME stat -c "%u:%g" "$HOME")}
 
 # does host's user exist in docker?  (i.e., dbadmin, ftp, root)
 if ! docker exec -i -u $LOGNAME "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo true >/dev/null 2>&1; then
   # add group if we need to and its safe
-  if [[ $HOME_GROUP != $(docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME stat -c "%G" "$HOME") ]] && [[ ${USERID#*:} -ge 20 ]] ; then
+  if [[ $LOGGROUP != $(docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME stat -c "%G" "$HOME") ]] && [[ ${USERID#*:} -ge 20 ]] ; then
     # it's optional but nice to see group names correct on files, but don't
     # touch group names in /etc/passwd that are <20.  However, 14 is
     # available, so renumber whatever has ${USERID#*:} to 14 and then add the group
     docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME bash -c 'sudo groupmod -g 14 $(getent group "'"${USERID#*:}"'" | cut -d: -f1) 2>/dev/null' # change gid of group
   fi
-  docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo groupadd --gid "${USERID#*:}" "$HOME_GROUP"
+  docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo groupadd --gid "${USERID#*:}" "$LOGGROUP"
 
   # make a host user to match home directory ownership
   docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo useradd --uid "${USERID%%:*}" --gid "${USERID#*:}" --home-dir "$HOME" --no-create-home "$LOGNAME" || abort $? "Could not create user $LOGNAME ($USERID)"
 fi
+
+# add user to sudoers
+docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo bash -c "echo '$LOGNAME ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers" || abort $? "Could not give $LOGNAME sudo access"
 
 # a temporary fix to allow restarts of the docker container
 docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sed -i.bak 's/\(cp.*\)/\1 || true/' /opt/vertica/bin/docker-entrypoint.sh
