add settings to ssh to avoid the fingerprint warning
Also applied best practices to quoting strings in bash and makefiles

diff --git a/bin/vertica-install b/bin/vertica-install
--- a/bin/vertica-install
+++ b/bin/vertica-install
@@ -6,8 +6,8 @@
 # defaults that can be overridden with environment variables.
 : ${VERTICA_PORT:=${VSQL_PORT:-5433}}
 : ${SSHD_PORT:=5432}
-: ${CONTAINER_NAME:=vertica-demo}
-: ${HOST_NAME:=$CONTAINER_NAME}
+: ${VERTICA_CONTAINER_NAME:=vertica-demo}
+: ${HOST_NAME:=$VERTICA_CONTAINER_NAME}
 : ${DB_NAME:=demo}
 : ${DOCKER_IMAGE:=vertica/vertica-k8s:latest} # see https://hub.docker.com/r/vertica/vertica-k8s
 
@@ -37,7 +37,7 @@ fi
 DOCKER_RUNARGS+=( -p "$VERTICA_PORT:5433" )
 DOCKER_RUNARGS+=( -p "$((VERTICA_PORT+11)):5444" )
 DOCKER_RUNARGS+=( -p "$SSHD_PORT:22" )
-DOCKER_RUNARGS+=( --name "$CONTAINER_NAME" )
+DOCKER_RUNARGS+=( --name "$VERTICA_CONTAINER_NAME" )
 DOCKER_RUNARGS+=( --hostname "$HOST_NAME" )
 
 # mount the home directory unless the user is dbadmin because this docker
@@ -47,7 +47,7 @@ if [[ $HOME != dbadmin ]] ; then
 fi
 
 # clear out old container in case it had issues
-docker container rm $CONTAINER_NAME 2>/dev/null
+docker container rm $VERTICA_CONTAINER_NAME 2>/dev/null
 
 docker run --detach "${DOCKER_RUNARGS[@]}" "${VERTICA_ENV[@]}" "$DOCKER_IMAGE" || abort $? "Could not create docker"
 
@@ -61,35 +61,35 @@ else
 fi
 
 # determine uid/gid of mounted home directory (in case docker maps to a different id)
-: ${USERID:=$(docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME stat -c "%u:%g" "$HOME")}
+: ${USERID:=$(docker exec -i "${VERTICA_ENV[@]}" $VERTICA_CONTAINER_NAME stat -c "%u:%g" "$HOME")}
 
 # If the home directory mount is owned by non-root, make it look like it's
 # owned by the actual owner by creating an account within the container.
 if [[ $USERID =~ ^[1-9][0-9]*: ]] ; then
   # does host's user exist in docker?  (i.e., dbadmin, ftp, root)
-  if ! docker exec -i -u $LOGNAME "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo true >/dev/null 2>&1; then
+  if ! docker exec -i -u $LOGNAME "${VERTICA_ENV[@]}" $VERTICA_CONTAINER_NAME sudo true >/dev/null 2>&1; then
     # add group if we need to and its safe
-    if [[ $LOGGROUP != $(docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME stat -c "%G" "$HOME") ]] && [[ ${USERID#*:} -ge 20 ]] ; then
+    if [[ $LOGGROUP != $(docker exec -i "${VERTICA_ENV[@]}" $VERTICA_CONTAINER_NAME stat -c "%G" "$HOME") ]] && [[ ${USERID#*:} -ge 20 ]] ; then
       # it's optional but nice to see group names correct on files, but don't
       # touch group names in /etc/passwd that are <20.  However, 14 is
       # available, so renumber whatever has ${USERID#*:} to 14 and then add the group
-      docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME bash -c 'sudo groupmod -g 14 $(getent group "'"${USERID#*:}"'" | cut -d: -f1) 2>/dev/null' # change gid of group
+      docker exec -i "${VERTICA_ENV[@]}" $VERTICA_CONTAINER_NAME bash -c 'sudo groupmod -g 14 $(getent group "'"${USERID#*:}"'" | cut -d: -f1) 2>/dev/null' # change gid of group
     fi
-    docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo groupadd --gid "${USERID#*:}" "$LOGGROUP"
+    docker exec -i "${VERTICA_ENV[@]}" $VERTICA_CONTAINER_NAME sudo groupadd --gid "${USERID#*:}" "$LOGGROUP"
 
     # make a host user to match home directory ownership
-    docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo useradd --uid "${USERID%%:*}" --gid "${USERID#*:}" --home-dir "$HOME" --no-create-home "$LOGNAME" || abort $? "Could not create user $LOGNAME ($USERID)"
+    docker exec -i "${VERTICA_ENV[@]}" $VERTICA_CONTAINER_NAME sudo useradd --uid "${USERID%%:*}" --gid "${USERID#*:}" --home-dir "$HOME" --no-create-home "$LOGNAME" || abort $? "Could not create user $LOGNAME ($USERID)"
   fi
 
   # add user to sudoers
-  docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo bash -c "echo '$LOGNAME ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers" || abort $? "Could not give $LOGNAME sudo access"
+  docker exec -i "${VERTICA_ENV[@]}" $VERTICA_CONTAINER_NAME sudo bash -c "echo '$LOGNAME ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers" || abort $? "Could not give $LOGNAME sudo access"
 fi
 
 # this allows ssh commands to succeed
-docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo bash -c 'echo "LANG=en_US.UTF-8" >> /etc/environment'
+docker exec -i "${VERTICA_ENV[@]}" $VERTICA_CONTAINER_NAME sudo bash -c 'echo "LANG=en_US.UTF-8" >> /etc/environment'
 
 # a temporary fix to allow restarts of the docker container
-docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sed -i.bak 's/\(cp.*\)/\1 || true/' /opt/vertica/bin/docker-entrypoint.sh
+docker exec -i "${VERTICA_ENV[@]}" $VERTICA_CONTAINER_NAME sed -i.bak 's/\(cp.*\)/\1 || true/' /opt/vertica/bin/docker-entrypoint.sh
 
 # create the database
-docker exec -i "${VERTICA_ENV[@]}" "$CONTAINER_NAME" opt/vertica/bin/admintools -t create_db --database="$DB_NAME" --password= --hosts=localhost || exit $?
+docker exec -i "${VERTICA_ENV[@]}" "$VERTICA_CONTAINER_NAME" opt/vertica/bin/admintools -t create_db --database="$DB_NAME" --password= --hosts=localhost || exit $?
diff --git a/bin/verticalab b/bin/verticalab
--- a/bin/verticalab
+++ b/bin/verticalab
@@ -2,11 +2,10 @@
 
 # defaults that can be overridden with environment variables.
 : ${FROM_HOME:=false}
-
-# defaults
-CONTAINER_NAME=verticalab
-DEMO_IMG=verticapy-jupyterlab
-PORT=8889
+: ${VERTICA_CONTAINER_NAME:=verticalab}
+: ${VERTICAPY_CONTAINER_NAME:=verticapy-demo}
+: ${DEMO_IMG:=verticapy-jupyterlab}
+: ${PORT:=8889}
 
 function usage {
     echo "usage: $0 [-h] [-c <container>][-i <image>] [-p <port>]"
@@ -31,7 +30,7 @@ while getopts "p:c:i:h" opt; do
             PORT=$OPTARG
             ;;
         c)
-            CONTAINER_NAME=$OPTARG
+            VERTICAPY_CONTAINER_NAME=$OPTARG
             ;;
         \?)
             echo "Unknown option: -${opt}"
@@ -45,24 +44,26 @@ if [[ $FROM_HOME = true ]] ; then
 fi
 
 # make sure vertica-demo is running
-if ! docker exec -i vertica-demo true; then
-  echo "Cannot access vertica-demo.  Did you run vertica-install?" >&2
+if ! docker exec -i "$VERTICA_CONTAINER_NAME" true; then
+  echo "Cannot access $VERTICA_CONTAINER_NAME.  Did you run vertica-install?" >&2
   exit 1
 fi
 
-docker run -d -it --rm -p $PORT:8888 $VOL_FLAG --name $CONTAINER_NAME $DEMO_IMG || exit $?
+docker run -d -it --rm -p $PORT:8888 $VOL_FLAG --name "$VERTICAPY_CONTAINER_NAME" "$DEMO_IMG" || exit $?
 
 # copy dbadmin@vertica-demo credentials to root@verticapy-demo to enable ssh
-docker exec -i vertica-demo bash -c "cd; tar -zcf - .ssh" | docker exec -i $CONTAINER_NAME bash -c "cd; tar -zxf -"
+docker exec -i "$VERTICA_CONTAINER_NAME" bash -c "cd; tar -zcf - .ssh" | docker exec -i "$VERTICAPY_CONTAINER_NAME" bash -c "cd; tar -zxf -"
+# tweak some settings to disable the fingerprint warnings
+docker exec -i "$VERTICAPY_CONTAINER_NAME" bash -c 'printf "%s\n" "Host *" "    GlobalKnownHostsFile=/dev/nulls" "    UserKnownHostsFile=/dev/null" "    UpdateHostKeys=no" "    StrictHostKeyChecking=no" "    LogLevel=error" >> $HOME/.ssh/config; chmod 400 $HOME/.ssh/config'
 
 # sleep some time to wait for jupyterlab logs
 timeout=10 #seconds
-while ! docker logs -n 5 $CONTAINER_NAME | grep -Eo 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+?.*' >/dev/null && ((timeout--)); do
+while ! docker logs -n 5 "$VERTICAPY_CONTAINER_NAME" | grep -Eo 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+?.*' >/dev/null && ((timeout--)); do
   sleep 1
   echo "Starting..."
 done
 
 echo
 echo "copy and paste one of these URLs: "
-docker logs -n 5 $CONTAINER_NAME | grep -Eo 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+?.*' | sed "s/:8888/:${PORT}/" || exit $?
+docker logs -n 5 "$VERTICAPY_CONTAINER_NAME" | grep -Eo 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+?.*' | sed "s/:8888/:${PORT}/" || exit $?
 
