Creating a configuration file
Default configuration file (essentially empty) in git
Makefile creates config file from default with cp
All scripts source the same config file so env variables do not need to
  be used and each script knows the whole config such as port numbers
.gitignore updated so git doesn't complain about it
Will later be used to track EULA acceptance

diff --git a/bin/vertica-install b/bin/vertica-install
--- a/bin/vertica-install
+++ b/bin/vertica-install
@@ -1,16 +1,28 @@
 #!/bin/bash
 
-# this script runs the docker environment and sets up an identical user and
-# home directory so it behaves a lot like running vsql in your own directory
+# this script sets up a docker container running vertica
+
+# Find the config file
+VERTICA_DEMO_PREFIX=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+VERTICA_DEMO_PREFIX=${VERTICA_DEMO_PREFIX%/bin}
+CONFIG_FILE=$VERTICA_DEMO_PREFIX/etc/vertica-demo.conf
+if ! [[ -r $CONFIG_FILE ]]; then
+  if ! make -C $VERTICA_DEMO_PREFIX etc/vertica-demo.conf || ! [[ -r $CONFIG_FILE ]]; then
+    echo "Cannot find config file ($CONFIG_FILE)" >&2
+    exit 1
+  fi
+fi
+# Load the configuration
+source $CONFIG_FILE
 
 # defaults that can be overridden with environment variables.
 : ${VERTICA_PORT:=${VSQL_PORT:-5433}}
-: ${SSHD_PORT:=5432}
+: ${VERTICA_SSH_PORT:=5432}
 : ${VERTICALAB_CONTAINER_NAME:=verticalab}
 : ${VERTICA_CONTAINER_NAME:=vertica-demo}
 : ${VERTICA_HOST_NAME:=$VERTICA_CONTAINER_NAME}
 : ${DB_NAME:=demo}
-: ${DOCKER_IMAGE:=vertica/vertica-k8s:latest} # see https://hub.docker.com/r/vertica/vertica-k8s
+: ${VERTICA_DOCKER_IMAGE:=vertica/vertica-k8s:latest} # see https://hub.docker.com/r/vertica/vertica-k8s
 
 function abort {
   local retval=$1
@@ -37,7 +49,7 @@ fi
 
 DOCKER_RUNARGS+=( -p "$VERTICA_PORT:5433" )
 DOCKER_RUNARGS+=( -p "$((VERTICA_PORT+11)):5444" )
-DOCKER_RUNARGS+=( -p "$SSHD_PORT:22" )
+DOCKER_RUNARGS+=( -p "$VERTICA_SSH_PORT:22" )
 DOCKER_RUNARGS+=( --name "$VERTICA_CONTAINER_NAME" )
 DOCKER_RUNARGS+=( --hostname "$VERTICA_HOST_NAME" )
 
@@ -50,7 +62,7 @@ fi
 # clear out old container in case it had issues
 docker container rm $VERTICA_CONTAINER_NAME 2>/dev/null
 
-docker run --detach "${DOCKER_RUNARGS[@]}" "${VERTICA_ENV[@]}" "$DOCKER_IMAGE" || abort $? "Could not create docker"
+docker run --detach "${DOCKER_RUNARGS[@]}" "${VERTICA_ENV[@]}" "$VERTICA_DOCKER_IMAGE" || abort $? "Could not create docker"
 
 # SSH tweaks
 # don't use DNS in sshd because it slows down ssh
diff --git a/bin/vertica-stop b/bin/vertica-stop
--- a/bin/vertica-stop
+++ b/bin/vertica-stop
@@ -1,5 +1,20 @@
 #!/bin/bash
 
+# this script stops the vertica docker container
+
+# Find the config file
+VERTICA_DEMO_PREFIX=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+VERTICA_DEMO_PREFIX=${VERTICA_DEMO_PREFIX%/bin}
+CONFIG_FILE=$VERTICA_DEMO_PREFIX/etc/vertica-demo.conf
+if ! [[ -r $CONFIG_FILE ]]; then
+  if ! make -C $VERTICA_DEMO_PREFIX etc/vertica-demo.conf || ! [[ -r $CONFIG_FILE ]]; then
+    echo "Cannot find config file ($CONFIG_FILE)" >&2
+    exit 1
+  fi
+fi
+# Load the configuration
+source $CONFIG_FILE
+
 : ${CONTAINER_NAME:=vertica-demo}
 : ${DBNAME:=demo} # default database name
 
diff --git a/bin/verticalab b/bin/verticalab
--- a/bin/verticalab
+++ b/bin/verticalab
@@ -1,11 +1,26 @@
 #!/bin/bash
 
+# this script sets up a docker container with an ML development environment
+
+# Find the config file
+VERTICA_DEMO_PREFIX=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+VERTICA_DEMO_PREFIX=${VERTICA_DEMO_PREFIX%/bin}
+CONFIG_FILE=$VERTICA_DEMO_PREFIX/etc/vertica-demo.conf
+if ! [[ -r $CONFIG_FILE ]]; then
+  if ! make -C $VERTICA_DEMO_PREFIX etc/vertica-demo.conf || ! [[ -r $CONFIG_FILE ]]; then
+    echo "Cannot find config file ($CONFIG_FILE)" >&2
+    exit 1
+  fi
+fi
+# Load the configuration
+source $CONFIG_FILE
+
 # defaults that can be overridden with environment variables.
 : ${VERTICALAB_CONTAINER_NAME:=verticalab}
+: ${VERTICALAB_IMG:=verticapy-jupyterlab}
 : ${VERTICA_CONTAINER_NAME:=vertica-demo}
 : ${VERTICA_HOST_NAME:=$VERTICA_CONTAINER_NAME}
-: ${DEMO_IMG:=verticapy-jupyterlab}
-: ${PORT:=8889}
+: ${VERTICALAB_PORT:=8889}
 : ${DOCKER_HOSTNAME:=host.docker.internal} # for docker-machine use $(docker-machine ip)
 : ${VERTICA_SSH_PORT:=5432}
 : ${VOL:=false}
@@ -30,10 +45,10 @@ while getopts "p:c:i:h" opt; do
             usage
             ;;
         i)
-            DEMO_IMG=$OPTARG
+            VERTICALAB_IMG=$OPTARG
             ;;
         p)
-            PORT=$OPTARG
+            VERTICALAB_PORT=$OPTARG
             ;;
         c)
             VERTICALAB_CONTAINER_NAME=$OPTARG
@@ -49,7 +64,7 @@ if [[ $VOL = true ]] ; then
     VOL_FLAG="-v $VOL_PATH:/project"
 fi
 
-docker run -d -it --rm -p $PORT:8888 $VOL_FLAG --name "$VERTICALAB_CONTAINER_NAME" "$DEMO_IMG" || exit $?
+docker run -d -it --rm -p $VERTICALAB_PORT:8888 $VOL_FLAG --name "$VERTICALAB_CONTAINER_NAME" "$VERTICALAB_IMG" || exit $?
 
 # if vertica-demo is running
 if docker exec -i "$VERTICA_CONTAINER_NAME" true 2>/dev/null; then
@@ -70,7 +85,7 @@ done
 echo
 echo "Waiting for url to open in browser..."
 # Create an array that will contain the urls. 
-declare -a VERTICALAB_URLS=($(docker logs -n 5 "$VERTICALAB_CONTAINER_NAME" | grep -Eo 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+?.*' | sed "s/:8888/:${PORT}/"))
+declare -a VERTICALAB_URLS=($(docker logs -n 5 "$VERTICALAB_CONTAINER_NAME" | grep -Eo 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+?.*' | sed "s/:8888/:${VERTICALAB_PORT}/"))
 KERNEL=$(uname -s)
 # This checks the kernel name to set the correct command to open the link in browser,
 # because Linux systems will use xdg-open while MacOs will use open
diff --git a/bin/vsql b/bin/vsql
--- a/bin/vsql
+++ b/bin/vsql
@@ -4,21 +4,25 @@
 # docker environment seamlessly.  It works by checking the name it was
 # executed as, so a symbolic link "vsql" will run vsql.
 
-# You can override some options with environment variables if you like.  For
-# instance, if you create a vertica user "bob" and want to always run vsql as
-# bob, you could set VSQL_USER:
-# export VSQL_USER=bob
+# Find the config file
+VERTICA_DEMO_PREFIX=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+VERTICA_DEMO_PREFIX=${VERTICA_DEMO_PREFIX%/bin}
+CONFIG_FILE=$VERTICA_DEMO_PREFIX/etc/vertica-demo.conf
+if ! [[ -r $CONFIG_FILE ]]; then
+  if ! make -C $VERTICA_DEMO_PREFIX etc/vertica-demo.conf || ! [[ -r $CONFIG_FILE ]]; then
+    echo "Cannot find config file ($CONFIG_FILE)" >&2
+    exit 1
+  fi
+fi
+# Load the configuration
+source $CONFIG_FILE
 
-: ${CONTAINER_NAME:=vertica-demo}
+: ${VERTICA_CONTAINER_NAME:=vertica-demo}
 : ${EXECNAME:=${BASH_SOURCE[0]##*/}}
+: ${VSQL_USER:=dbadmin}
 
 # Special cases for certain executables
 case "$EXECNAME" in
-  ( vsql ) : 
-      # run vsql as local user, but connect to Vertica as dbadmin
-      : ${VSQL_USER:=dbadmin}
-      export VSQL_USER
-    ;;
   ( admintools ) :
       # always run admintools as dbadmin
       USERID=dbadmin
@@ -40,7 +44,7 @@ if [[ $MACHTYPE =~ ^aarch64 ]] || [[ $MACHTYPE =~ ^arm64 ]] ; then
   VERTICA_ENV+=(-e VERTICA_MEMDEBUG=2)
 fi
 
-: ${USERID:=$(docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME stat -c "%u:%g" "$HOME")}
+: ${USERID:=$(docker exec -i "${VERTICA_ENV[@]}" $VERTICA_CONTAINER_NAME stat -c "%u:%g" "$HOME")}
 DOCKER_EXECARGS+=( -u "$USERID" )
 
 test -t 0 && DOCKER_EXECARGS+=( -t )
@@ -54,4 +58,4 @@ else
   EXECNAME=bash
 fi
 
-docker exec -i "${DOCKER_EXECARGS[@]}" "${VERTICA_ENV[@]}" $CONTAINER_NAME $EXECNAME "$@"
+docker exec -i "${DOCKER_EXECARGS[@]}" "${VERTICA_ENV[@]}" $VERTICA_CONTAINER_NAME $EXECNAME "$@"
