move all defaults into conf file
Reduce the redundancy of the default values by moving everything into
the conf file.  When a git-pull causes the conf file to change, we throw
an error that the conf file needs to be manually updated instead of
ignoring the changes of overwriting the configuration.

When a new conf file is created, remove any stopped vertica-demo
containers so that a vertica-start will use the new config.

Fixed a couple instances where the image name didn't start with vertica/

Require a version specified if we are building a new verticalab

Fixed a bad variable name "CONTAINER_NAME" that should have been
"VERTICA_CONTAINER_NAME"

When an open command doesn't exist (linux without X), then change the
text "if this link doesn't open" to just "copy/paste this"

hide some strange output like "is not running" in vertica-start

Fixed shutdown functionality in vertica-start if database is running

diff --git a/bin/vertica-start b/bin/vertica-start
--- a/bin/vertica-start
+++ b/bin/vertica-start
@@ -13,11 +13,7 @@ if ! [[ -r $CONFIG_FILE ]]; then
   fi
 fi
 # Load the configuration
-source $CONFIG_FILE
-
-# defaults
-: ${VERTICA_CONTAINER_NAME:=vertica-demo}
-: ${DB_NAME:=demo} # default database name
+source $CONFIG_FILE || abort $? "Cannot load config file $CONFIG_FILE"
 
 # allow for enviornment variables to be
 # specified in VERTICA_ENV_FORWARDING
@@ -35,8 +31,8 @@ if [[ $MACHTYPE =~ ^aarch64 ]] || [[ $MACHTYPE =~ ^arm64 ]] ; then
 fi
 
 # try to stop gracefully if running
-if docker exec -i ${VERTICA_ENV[@]} $VERTICA_CONTAINER_NAME opt/vertica/bin/admintools -t db_status -s $DB_NAME | grep -q "^$DB_NAME\$" 2>/dev/null; then
-  docker exec -i ${VERTICA_ENV[@]} $VERTICA_CONTAINER_NAME opt/vertica/bin/admintools -t stop_db --database=$DB_NAME --password= 2>/dev/null
+if docker exec -i ${VERTICA_ENV[@]} $VERTICA_CONTAINER_NAME opt/vertica/bin/admintools -t db_status -s UP 2>/dev/null | grep -q "^$DB_NAME\$" ; then
+  docker exec -i ${VERTICA_ENV[@]} $VERTICA_CONTAINER_NAME opt/vertica/bin/admintools -t stop_db --database=$DB_NAME --password=
 fi
 
 docker restart $VERTICA_CONTAINER_NAME || exit $?
diff --git a/bin/verticalab b/bin/verticalab
--- a/bin/verticalab
+++ b/bin/verticalab
@@ -13,19 +13,7 @@ if ! [[ -r $CONFIG_FILE ]]; then
   fi
 fi
 # Load the configuration
-source $CONFIG_FILE
-
-# defaults that can be overridden with environment variables.
-: ${VERTICALAB_CONTAINER_NAME:=verticalab}
-: ${VERTICALAB_IMG:=verticapy-jupyterlab}
-: ${VERTICALAB_IMG_VERSION:=latest}
-: ${VERTICA_CONTAINER_NAME:=vertica-demo}
-: ${VERTICA_HOST_NAME:=$VERTICA_CONTAINER_NAME}
-: ${VERTICALAB_PORT:=8889}
-: ${VERTICALAB_BIND_ADDRESS:=127.0.0.1}
-: ${VERTICA_PORT:=5433}
-: ${VERTICA_SSH_PORT:=$((VERTICA_PORT-1))}
-: ${DOCKER_NETWORK:=demo}
+source $CONFIG_FILE || abort $? "Cannot load config file $CONFIG_FILE"
 
 function usage {
     echo "usage: $0 [-h] [-c <container>][-i <image>] [-p <port>]"
@@ -72,7 +60,8 @@ if [[ -n $DOCKER_HOST ]] && [[ $VERTICALAB_BIND_ADDRESS == 127.0.0.1 ]]; then
   VERTICALAB_BIND_ADDRESS=${VERTICALAB_BIND_ADDRESS%%:*}
 fi
 
-if [[ $VERTICALAB_PORT =~ ^[0-9]*$ ]] ; then VERTICALAB_RUNARGS+=( -p $VERTICALAB_BIND_ADDRESS:$VERTICALAB_PORT:8888 )
+if [[ $VERTICALAB_PORT =~ ^[0-9]*$ ]] ; then
+  VERTICALAB_RUNARGS+=( -p $VERTICALAB_BIND_ADDRESS:$VERTICALAB_PORT:8888 )
 else
   echo "Warning: VERTICALAB_PORT must be numeric.  Using a random port." >&2
   VERTICALAB_RUNARGS+=( --expose 8888 -P )
@@ -85,7 +74,7 @@ VERTICALAB_RUNARGS+=( --rm )
 docker network create "$DOCKER_NETWORK" 2>/dev/null
 VERTICALAB_RUNARGS+=( --network "$DOCKER_NETWORK" )
 
-docker run --detach "${VERTICALAB_RUNARGS[@]}" "$VERTICALAB_IMG:$VERTICALAB_IMG_VERSION" || exit $?
+docker run --detach "${VERTICALAB_RUNARGS[@]}" "vertica/$VERTICALAB_IMG:$VERTICALAB_IMG_VERSION" || exit $?
 
 VERTICALAB_PORT=$(docker port "$VERTICALAB_CONTAINER_NAME" 8888/tcp)
 VERTICALAB_PORT=${VERTICALAB_PORT##*:}
@@ -132,8 +121,6 @@ while ! docker logs -n 5 "$VERTICALAB_CONTAINER_NAME" 2>&1 | grep 'Or copy and p
   sleep 1
 done
 
-echo
-echo "Waiting for url to open in browser..."
 # Get the basic URL and remap the hostname and port
 URL=$(docker logs -n 5 "$VERTICALAB_CONTAINER_NAME" 2>&1 | grep -Eo 'http[s]?://[0-9.]+:8888/.*' | sed "s/[0-9.]*:8888/$VERTICALAB_BIND_ADDRESS:$VERTICALAB_PORT/")
 # This checks the kernel name to set the correct command to open the link in browser,
@@ -147,7 +134,14 @@ else
 fi
 # Open the correct url in browser. We know that the correct url is the second one.
 # So even if in some cases a 3rd one is created this will not be affected
-$OPEN_CMD "$URL" 2> /dev/null
-echo
-echo "If the link does not open or does not work, copy and paste this URL in browser:"
+if [[ -x ${OPEN_CMD%% *} ]]; then
+  echo
+  echo "Waiting for url to open in browser..."
+  $OPEN_CMD "$URL" 2> /dev/null
+  echo
+  echo "If the link does not open or does not work, copy and paste this URL in browser:"
+else
+  echo
+  echo "Copy and paste this URL in browser:"
+fi
 echo "    $URL"
diff --git a/bin/verticalab-build b/bin/verticalab-build
--- a/bin/verticalab-build
+++ b/bin/verticalab-build
@@ -13,12 +13,7 @@ if ! [[ -r $CONFIG_FILE ]]; then
   fi
 fi
 # Load the configuration
-source $CONFIG_FILE
-
-# defaults that can be overridden with environment variables.
-: ${VERTICALAB_IMG:=verticapy-jupyterlab}
-: ${VERTICALAB_IMG_VERSION:=latest}
-: ${PYTHON_VERSION:=3.8-slim-buster}
+source $CONFIG_FILE || abort $? "Cannot load config file $CONFIG_FILE"
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
 REPO_DIR=$(dirname $SCRIPT_DIR)
@@ -32,6 +27,6 @@ fi
 # Specify the python base image version to use
 DOCKER_BUILDARGS+=( --build-arg PYTHON_VERSION=$PYTHON_VERSION )
 # The name of the image
-DOCKER_BUILDARGS+=( -t $VERTICALAB_IMG:$VERTICALAB_IMG_VERSION )
+DOCKER_BUILDARGS+=( -t vertica/$VERTICALAB_IMG:$VERTICALAB_IMG_VERSION )
 
 docker build "${DOCKER_BUILDARGS[@]}" $REPO_DIR/docker-verticapy/
