If home directory is mounted as root, don't create user account

diff --git a/bin/vertica-setup b/bin/vertica-setup
--- a/bin/vertica-setup
+++ b/bin/vertica-setup
@@ -63,23 +63,27 @@ fi
 # determine uid/gid of mounted home directory (in case docker maps to a different id)
 : ${USERID:=$(docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME stat -c "%u:%g" "$HOME")}
 
-# does host's user exist in docker?  (i.e., dbadmin, ftp, root)
-if ! docker exec -i -u $LOGNAME "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo true >/dev/null 2>&1; then
-  # add group if we need to and its safe
-  if [[ $LOGGROUP != $(docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME stat -c "%G" "$HOME") ]] && [[ ${USERID#*:} -ge 20 ]] ; then
-    # it's optional but nice to see group names correct on files, but don't
-    # touch group names in /etc/passwd that are <20.  However, 14 is
-    # available, so renumber whatever has ${USERID#*:} to 14 and then add the group
-    docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME bash -c 'sudo groupmod -g 14 $(getent group "'"${USERID#*:}"'" | cut -d: -f1) 2>/dev/null' # change gid of group
+# If the home directory mount is owned by non-root, make it look like it's
+# owned by the actual owner by creating an account within the container.
+if [[ $USERID =~ ^[1-9][0-9]*: ]] ; then
+  # does host's user exist in docker?  (i.e., dbadmin, ftp, root)
+  if ! docker exec -i -u $LOGNAME "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo true >/dev/null 2>&1; then
+    # add group if we need to and its safe
+    if [[ $LOGGROUP != $(docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME stat -c "%G" "$HOME") ]] && [[ ${USERID#*:} -ge 20 ]] ; then
+      # it's optional but nice to see group names correct on files, but don't
+      # touch group names in /etc/passwd that are <20.  However, 14 is
+      # available, so renumber whatever has ${USERID#*:} to 14 and then add the group
+      docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME bash -c 'sudo groupmod -g 14 $(getent group "'"${USERID#*:}"'" | cut -d: -f1) 2>/dev/null' # change gid of group
+    fi
+    docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo groupadd --gid "${USERID#*:}" "$LOGGROUP"
+
+    # make a host user to match home directory ownership
+    docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo useradd --uid "${USERID%%:*}" --gid "${USERID#*:}" --home-dir "$HOME" --no-create-home "$LOGNAME" || abort $? "Could not create user $LOGNAME ($USERID)"
   fi
-  docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo groupadd --gid "${USERID#*:}" "$LOGGROUP"
 
-  # make a host user to match home directory ownership
-  docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo useradd --uid "${USERID%%:*}" --gid "${USERID#*:}" --home-dir "$HOME" --no-create-home "$LOGNAME" || abort $? "Could not create user $LOGNAME ($USERID)"
+  # add user to sudoers
+  docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo bash -c "echo '$LOGNAME ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers" || abort $? "Could not give $LOGNAME sudo access"
 fi
-
-# add user to sudoers
-docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sudo bash -c "echo '$LOGNAME ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers" || abort $? "Could not give $LOGNAME sudo access"
 
 # a temporary fix to allow restarts of the docker container
 docker exec -i "${VERTICA_ENV[@]}" $CONTAINER_NAME sed -i.bak 's/\(cp.*\)/\1 || true/' /opt/vertica/bin/docker-entrypoint.sh
