Enable ssh from verticapy-demo to vertica-demo
Provide credentials so a password isn't needed
Fix the locale issue, although I suspect there is a better
  way to fix it, but this works for now.
ssh is NOT yet installed on verticapy-demo, so that will be done in a
  separate commit

diff --git a/bin/verticalab b/bin/verticalab
--- a/bin/verticalab
+++ b/bin/verticalab
@@ -44,13 +44,25 @@ if [[ $FROM_HOME = true ]] ; then
     VOL_FLAG="-v $HOME:/project"
 fi
 
+# make sure vertica-demo is running
+if ! docker exec -i vertica-demo true; then
+  echo "Cannot access vertica-demo.  Did you run vertica-install?" >&2
+  exit 1
+fi
+
 docker run -d -it --rm -p $PORT:8888 $VOL_FLAG --name $CONTAINER_NAME $DEMO_IMG || exit $?
 
+# copy dbadmin@vertica-demo credentials to root@verticapy-demo to enable ssh
+docker exec -i vertica-demo bash -c "cd; tar -zcf - .ssh" | docker exec -i $CONTAINER_NAME bash -c "cd; tar -zxf -"
+
 # sleep some time to wait for jupyterlab logs
-echo "Waiting for the links..."
-sleep 10
+timeout=10 #seconds
+while ! docker logs -n 5 $CONTAINER_NAME | grep -Eo 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+?.*' >/dev/null && ((timeout--)); do
+  sleep 1
+  echo "Starting..."
+done
 
 echo
 echo "copy and paste one of these URLs: "
-docker logs -n 5 $CONTAINER_NAME | grep -Eo 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+?.*' | sed "s/8888/${PORT}/" || exit $?
+docker logs -n 5 $CONTAINER_NAME | grep -Eo 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+?.*' | sed "s/:8888/:${PORT}/" || exit $?
 
